allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ethersphere/bee-dashboard@0.36.1'
onlyBuiltDependencies:
  - '@ethersphere/bee-dashboard'
  - esbuild
  - unrs-resolver
