allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ethersphere/bee-dashboard@0.37.0'
  - '@solarpunkltd/file-manager-lib@1.1.0'
onlyBuiltDependencies:
  - '@ethersphere/bee-dashboard'
  - esbuild
  - unrs-resolver
